<template>
  <NucGridPage v-bind:gap="{'col':0,'row':0}" v-bind:rows="[1]"
    v-bind:schema="{'r0-c0':{'col':0,'row':0,'showIn':['xs','sm','md','lg'],'colSpan':1,'rowSpan':1}}"
    v-bind:columns="[1]" overflow="auto" v-bind:designMode="false" v-bind:minNsLimit="1330"
    v-bind:style="{'background':'#FFFFFF','paddingTop':'0px','paddingLeft':'0px','paddingRight':'0px','paddingBottom':'0px'}">
    <NucGridCell v-bind:wrap="true" v-bind:reverse="false" overflow="hidden" direction="column"
      v-bind:showInDevice="['xs','sm','md','lg']" verticalAlignment="top" horizontalAlignment="left"
      id="b23e7a1e-4cb2-4d08-8e97-aa527ad99962" v-bind:col="0" v-bind:row="0" v-bind:colSpan="1" v-bind:rowSpan="1"
      v-bind:marginTop="0" v-bind:marginLeft="0" v-bind:marginRight="0" v-bind:marginBottom="0"
      v-bind:style="{'height':'auto','background':'transparent','paddingTop':'0px','borderColor':'','borderStyle':'solid','borderWidth':'0px','paddingLeft':'0px','borderRadius':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'1px','borderTopRightRadius':'1px','borderBottomLeftRadius':'1px','borderBottomRightRadius':'1px'}"
      slot="r0-c0" area="r0-c0">
      <NucGroupElement top="0%" left="0%" v-bind:snapX="false" v-bind:snapY="false" v-bind:isLock="true" bgColor=""
        position="absolute" borderWidth="1px" ncTooltipText="" id="3eb40cdd-fca5-4a03-8895-b8b3fe1cc09e"
        v-bind:style="{'color':'#FFFFFF','width':'1330px','height':'802.75px','zIndex':2,'fontSize':'10.683225px','maxWidth':'','minWidth':'0px','tabIndex':'-0.712215','boxShadow':'0 0 0 0 rgba(0,0,0,0.5), inset 0 0 0 0 rgba(0,0,0,0.5)','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'0px','textAlign':'center','background':'','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.8902687499999999','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderColor':'#767676','borderStyle':'solid','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.95px','textDecoration':'none','borderLeftWidth':'0.95px','borderRightWidth':'0.95px','borderBottomWidth':'0.95px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}">
        <NucGroupElement top="0%" left="0%" v-bind:snapX="false" v-bind:snapY="false" bgColor="" position="absolute"
          borderWidth="0px" ncTooltipText="" id="ba6b24c3-0e70-4bf9-b74c-6baaa359d302"
          v-bind:style="{'color':'#FFFFFF','width':'1330px','height':'239.39999999999998px','zIndex':4,'fontSize':'10.683225px','maxWidth':'','minWidth':'1330px','tabIndex':'-0.712215','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'239.39999999999998px','textAlign':'center','background':'#f1c50e','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.8902687499999999','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderColor':'#767676','borderStyle':'solid','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0px','textDecoration':'none','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}">
          <WLabel top="17.46031746031746%" left="37.568080357142854%" text=" Meet The Team" v-bind:snapX="false"
            v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            id="210e6546-f0aa-4049-82c7-8e76c7bb2e54"
            v-bind:style="{'color':'#000000','width':'329.65px','height':'36.1px','zIndex':6,'fontSize':'42.7329px','maxWidth':'','minWidth':'','fontStyle':'','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'OpenSans-Bold,Open Sans','fontWeight':'bold','lineHeight':'0.712215','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':''}"/>
        </NucGroupElement>
        <NucGroupElement top="16.02299528301887%" left="9.683035714285714%" v-bind:snapX="false" v-bind:snapY="false"
          bgColor="" position="absolute" borderWidth="0px" ncTooltipText="" id="e950676e-6221-47c6-bc8f-96f0ee315fce"
          v-bind:style="{'color':'#FFFFFF','width':'1072.59579px','height':'540.5711849999999px','zIndex':5,'fontSize':'10.683225px','maxWidth':'','minWidth':'7.1221499999999995','tabIndex':'-0.712215','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'7.1221499999999995','textAlign':'center','background':'#FFFFFF','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.8902687499999999','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderColor':'#767676','borderStyle':'solid','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0px','textDecoration':'none','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}">
          <WImage top="7.199715876924818%" left="4.5125062088884045%" v-bind:blank="false" v-bind:snapX="false"
            v-bind:snapY="false" v-bind:rounded="false" stretch="none"
            imageUrl="https://images01.nicepage.com/c461c07a441a5d220e8feb1a/23f2b6ec8f435911852884f1/2.jpg"
            position="absolute" v-bind:isEnabled="true" v-bind:thumbnail="false" blankColor="black"
            v-bind:aspectRatio="true" dataLoading="static" ncTooltipText="Please write a text to display in tooltip..."
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModelForDynamicType'},'propName':'imageUrl','displayName':'Value'}]}"
            ncClickBorderColor="black" ncHoverBorderColor="black" dataModelForDynamicType="string"
            id="536ca566-c80e-4e39-8152-6a915635d5d1"
            v-bind:style="{'width':'287.73486px','height':'287.73486px','zIndex':7,'maxWidth':'','minWidth':'','boxShadow':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','borderColor':'#4B74FF','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}"/>
          <WImage top="7.422047892735096%" left="37.118195917501865%" v-bind:blank="false" v-bind:snapX="false"
            v-bind:snapY="false" v-bind:rounded="false" stretch="none"
            imageUrl="https://images01.nicepage.com/c461c07a441a5d220e8feb1a/dee2a7ea9eea577cab16110a/fff.jpg"
            position="absolute" v-bind:isEnabled="true" v-bind:thumbnail="false" blankColor="black"
            v-bind:aspectRatio="true" dataLoading="static" ncTooltipText="Please write a text to display in tooltip..."
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModelForDynamicType'},'propName':'imageUrl','displayName':'Value'}]}"
            ncClickBorderColor="black" ncHoverBorderColor="black" dataModelForDynamicType="string"
            id="6144f7a8-9400-4fcf-9c0b-aeb902d0d370"
            v-bind:style="{'width':'287.73486px','height':'287.73486px','zIndex':8,'maxWidth':'','minWidth':'','boxShadow':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','borderColor':'#4B74FF','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}"/>
          <WImage top="7.290295587069746%" left="68.65870056557624%" v-bind:blank="false" v-bind:snapX="false"
            v-bind:snapY="false" v-bind:rounded="false" stretch="none"
            imageUrl="https://images01.nicepage.com/c461c07a441a5d220e8feb1a/47d488474b1750ad8f9a684f/fggf.jpg"
            position="absolute" v-bind:isEnabled="true" v-bind:thumbnail="false" blankColor="black"
            v-bind:aspectRatio="true" dataLoading="static" ncTooltipText="Please write a text to display in tooltip..."
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModelForDynamicType'},'propName':'imageUrl','displayName':'Value'}]}"
            ncClickBorderColor="black" ncHoverBorderColor="black" dataModelForDynamicType="string"
            id="a034c886-df2c-4959-b9f9-481225029a3b"
            v-bind:style="{'width':'287.73486px','height':'287.73486px','zIndex':9,'maxWidth':'','minWidth':'','boxShadow':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','borderColor':'#4B74FF','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}"/>
          <WLabel top="64.95043523629074%" left="11.662215087393959%" text="MARY BROWN" v-bind:snapX="false"
            v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            id="46bb4c88-15e8-4202-9f2a-b0f97dc69a47"
            v-bind:style="{'color':'#000000','width':'','height':'','zIndex':10,'fontSize':'19.942019999999996px','maxWidth':'','minWidth':'','fontStyle':'','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'bold','lineHeight':'0.712215','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':''}"/>
          <WLabel top="72.06524425405718%" left="12.723674559570433%" text="creative leader" v-bind:snapX="false"
            v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            id="303a2e4c-d929-440d-bc02-49266d915805"
            v-bind:style="{'color':'#36b04b','width':'','height':'','zIndex':11,'fontSize':'15.66873px','maxWidth':'','minWidth':'','fontStyle':'','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'bold','lineHeight':'0.712215','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':''}"/>
          <WLabel top="77.84825768185188%" left="6.8185277958455%"
            text="Glavi amet ritnisl libero molestie ante fringilla purus eros quis glavrid from amet iquam lorem bibendum"
            v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom"
            ncTooltipText=""
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            id="b1f17d47-3883-4717-a546-b197923a941e"
            v-bind:style="{'color':'#000000','width':'237.5px','height':'52.25px','zIndex':12,'fontSize':'14.25px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.9974999999999998','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
          <WLabel top="64.8515803059011%" left="43.88934250404794%" text="ANN RICHMOND" v-bind:snapX="false"
            v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            id="e65b4cb7-1396-442b-830b-4576c3819bf3"
            v-bind:style="{'color':'#000000','width':'','height':'','zIndex':13,'fontSize':'19.942019999999996px','maxWidth':'','minWidth':'','fontStyle':'','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'bold','lineHeight':'0.712215','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':''}"/>
          <WLabel top="71.87851827443227%" left="46.322257435059996%" text="creative leader" v-bind:snapX="false"
            v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            id="7618fea6-a700-4826-8687-92e2baf58d2c"
            v-bind:style="{'color':'#36b04b','width':'108.3px','height':'15.2px','zIndex':14,'fontSize':'15.66873px','maxWidth':'','minWidth':'','fontStyle':'','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'bold','lineHeight':'0.712215','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':''}"/>
          <WLabel top="77.65878573193838%" left="39.494042264631396%"
            text="Glavi amet ritnisl libero molestie ante fringilla purus eros quis glavrid from amet iquam lorem bibendum"
            v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom"
            ncTooltipText=""
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            id="af7e9506-713f-4918-8d36-e9427e4eb472"
            v-bind:style="{'color':'#000000','width':'237.5px','height':'52.25px','zIndex':15,'fontSize':'14.25px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.9974999999999998','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
          <WLabel top="65.08224181014361%" left="74.36582294247083%" text="BOB GREENFIELD" v-bind:snapX="false"
            v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            id="de058263-9e59-4b50-9103-854b009438d3"
            v-bind:style="{'color':'#000000','width':'','height':'','zIndex':16,'fontSize':'19.942019999999996px','maxWidth':'','minWidth':'','fontStyle':'','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'bold','lineHeight':'0.712215','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':''}"/>
          <WLabel top="72.23000247137325%" left="76.96757497335972%" text="creative leader" v-bind:snapX="false"
            v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            id="4251511a-8449-4880-880c-664da1a8ab9b"
            v-bind:style="{'color':'#36b04b','width':'108.3px','height':'14.25px','zIndex':17,'fontSize':'15.66873px','maxWidth':'','minWidth':'','fontStyle':'','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'bold','lineHeight':'0.712215','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':''}"/>
          <WLabel top="77.83727380069747%" left="71.02506262195713%"
            text="Glavi amet ritnisl libero molestie ante fringilla purus eros quis glavrid from amet iquam lorem bibendum"
            v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom"
            ncTooltipText=""
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            id="54acfa80-93d7-4ab2-9de7-b0cba5030a90"
            v-bind:style="{'color':'#000000','width':'237.5px','height':'52.25px','zIndex':18,'fontSize':'14.25px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.9974999999999998','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
          <WIconButton tag="button" top="88.54655792624324%" icon="fab fa-instagram" left="84.04489406163938%"
            v-bind:pill="false" size="md" text="       " type="button" v-bind:block="false" color="#FFFFFF"
            v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
            fontSize="12px" position="absolute" fontStyle="normal" iconColor="#36b04b" v-bind:isEnabled="true"
            background="Transparent" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400" layoutMode="left-to-right"
            lineHeight="1.2" textShadow="" borderColor="#6C757D" borderWidth="0px" iconFontSize="30px"
            ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
            iconFontFamily="font-awesome"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
            ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
            horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
            ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
            horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
            ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
            id="6afec6b6-da25-49e5-8623-eb8cd128678e"
            v-bind:style="{'width':'26.599999999999998px','height':'39.9px','zIndex':19,'maxWidth':'','minWidth':'1.9px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'solid','marginRight':'','paddingLeft':'0px','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'2.84886px','borderTopRightRadius':'2.84886px','borderBottomLeftRadius':'2.84886px','borderBottomRightRadius':'2.84886px'}"/>
          <WIconButton tag="button" top="88.55754180739764%" icon="fab fa-twitter" left="80.56574267565286%"
            v-bind:pill="false" size="md" text="       " type="button" v-bind:block="false" color="#FFFFFF"
            v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
            fontSize="12px" position="absolute" fontStyle="normal" iconColor="#36b04b" v-bind:isEnabled="true"
            background="transparent" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400" layoutMode="left-to-right"
            lineHeight="1.2" textShadow="" borderColor="#6C757D" borderWidth="0px" iconFontSize="30px"
            ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
            iconFontFamily="font-awesome"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
            ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
            horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
            ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
            horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
            ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
            id="1e58b269-ba00-4f6a-b264-691ccde54c43"
            v-bind:style="{'width':'30.4px','height':'39.9px','zIndex':20,'maxWidth':'','minWidth':'1.9px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'solid','marginRight':'','paddingLeft':'0px','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'2.84886px','borderTopRightRadius':'2.84886px','borderBottomLeftRadius':'2.84886px','borderBottomRightRadius':'2.84886px'}"/>
          <WIconButton tag="button" top="88.56852568855204%" icon="fab fa-facebook-f" left="77.34953431406468%"
            v-bind:pill="false" size="md" text="       " type="button" v-bind:block="false" color="#FFFFFF"
            v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
            fontSize="12px" position="absolute" fontStyle="normal" iconColor="#36b04b" v-bind:isEnabled="true"
            background="transparent" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400" layoutMode="left-to-right"
            lineHeight="1.2" textShadow="" borderColor="#6C757D" borderWidth="0px" iconFontSize="30px"
            ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
            iconFontFamily="font-awesome"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
            ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
            horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
            ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
            horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
            ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
            id="670dba81-be26-476c-83dc-a8a90253c095"
            v-bind:style="{'width':'27.549999999999997px','height':'39.9px','zIndex':21,'maxWidth':'','minWidth':'1.9px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'solid','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'2.84886px','borderTopRightRadius':'2.84886px','borderBottomLeftRadius':'2.84886px','borderBottomRightRadius':'2.84886px'}"/>
          <WIconButton tag="button" top="88.34884806546393%" icon="fab fa-instagram" left="53.09650008995419%"
            v-bind:pill="false" size="md" text="       " type="button" v-bind:block="false" color="#FFFFFF"
            v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
            fontSize="12px" position="absolute" fontStyle="normal" iconColor="#36b04b" v-bind:isEnabled="true"
            background="Transparent" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400" layoutMode="left-to-right"
            lineHeight="1.2" textShadow="" borderColor="#6C757D" borderWidth="0px" iconFontSize="30px"
            ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
            iconFontFamily="font-awesome"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
            ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
            horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
            ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
            horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
            ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
            id="443d4f9f-b823-4dc2-885f-a37f99fe8253"
            v-bind:style="{'width':'26.599999999999998px','height':'39.9px','zIndex':22,'maxWidth':'','minWidth':'1.9px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'solid','marginRight':'','paddingLeft':'0px','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'2.84886px','borderTopRightRadius':'2.84886px','borderBottomLeftRadius':'2.84886px','borderBottomRightRadius':'2.84886px'}"/>
          <WIconButton tag="button" top="88.35983194661834%" icon="fab fa-twitter" left="49.61596479331294%"
            v-bind:pill="false" size="md" text="       " type="button" v-bind:block="false" color="#FFFFFF"
            v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
            fontSize="12px" position="absolute" fontStyle="normal" iconColor="#36b04b" v-bind:isEnabled="true"
            background="transparent" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400" layoutMode="left-to-right"
            lineHeight="1.2" textShadow="" borderColor="#6C757D" borderWidth="0px" iconFontSize="30px"
            ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
            iconFontFamily="font-awesome"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
            ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
            horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
            ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
            horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
            ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
            id="cf2843e0-068e-4438-88cb-ee5b682a8729"
            v-bind:style="{'width':'30.4px','height':'39.9px','zIndex':23,'maxWidth':'','minWidth':'1.9px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'solid','marginRight':'','paddingLeft':'0px','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'2.84886px','borderTopRightRadius':'2.84886px','borderBottomLeftRadius':'2.84886px','borderBottomRightRadius':'2.84886px'}"/>
          <WIconButton tag="button" top="88.37081582777274%" icon="fab fa-facebook-f" left="46.39975643172477%"
            v-bind:pill="false" size="md" text="       " type="button" v-bind:block="false" color="#FFFFFF"
            v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
            fontSize="12px" position="absolute" fontStyle="normal" iconColor="#36b04b" v-bind:isEnabled="true"
            background="transparent" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400" layoutMode="left-to-right"
            lineHeight="1.2" textShadow="" borderColor="#6C757D" borderWidth="0px" iconFontSize="30px"
            ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
            iconFontFamily="font-awesome"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
            ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
            horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
            ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
            horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
            ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
            id="71402cb1-35d0-4646-a09b-37a606323fe9"
            v-bind:style="{'width':'27.549999999999997px','height':'39.9px','zIndex':24,'maxWidth':'','minWidth':'1.9px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'solid','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'2.84886px','borderTopRightRadius':'2.84886px','borderBottomLeftRadius':'2.84886px','borderBottomRightRadius':'2.84886px'}"/>
          <WIconButton tag="button" top="88.52459016393442%" icon="fab fa-instagram" left="18.909755186205178%"
            v-bind:pill="false" size="md" text="       " type="button" v-bind:block="false" color="#FFFFFF"
            v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
            fontSize="12px" position="absolute" fontStyle="normal" iconColor="#36b04b" v-bind:isEnabled="true"
            background="Transparent" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400" layoutMode="left-to-right"
            lineHeight="1.2" textShadow="" borderColor="#6C757D" borderWidth="0px" iconFontSize="30px"
            ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
            iconFontFamily="font-awesome"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
            ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
            horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
            ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
            horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
            ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
            id="5cc02aee-afba-451c-82ca-35469bb26cf7"
            v-bind:style="{'width':'26.599999999999998px','height':'39.9px','zIndex':25,'maxWidth':'','minWidth':'1.9px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'solid','marginRight':'','paddingLeft':'0px','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'2.84886px','borderTopRightRadius':'2.84886px','borderBottomLeftRadius':'2.84886px','borderBottomRightRadius':'2.84886px'}"/>
          <WIconButton tag="button" top="88.53557404508884%" icon="fab fa-twitter" left="15.430603800218657%"
            v-bind:pill="false" size="md" text="       " type="button" v-bind:block="false" color="#FFFFFF"
            v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
            fontSize="12px" position="absolute" fontStyle="normal" iconColor="#36b04b" v-bind:isEnabled="true"
            background="transparent" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400" layoutMode="left-to-right"
            lineHeight="1.2" textShadow="" borderColor="#6C757D" borderWidth="0px" iconFontSize="30px"
            ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
            iconFontFamily="font-awesome"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
            ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
            horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
            ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
            horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
            ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
            id="47da939f-7fe7-44a9-adc7-8257d63cd5a9"
            v-bind:style="{'width':'30.4px','height':'39.9px','zIndex':26,'maxWidth':'','minWidth':'1.9px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'solid','marginRight':'','paddingLeft':'0px','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'2.84886px','borderTopRightRadius':'2.84886px','borderBottomLeftRadius':'2.84886px','borderBottomRightRadius':'2.84886px'}"/>
          <WIconButton tag="button" top="88.54655792624324%" icon="fab fa-facebook-f" left="12.214395438630483%"
            v-bind:pill="false" size="md" text="       " type="button" v-bind:block="false" color="#FFFFFF"
            v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
            fontSize="12px" position="absolute" fontStyle="normal" iconColor="#36b04b" v-bind:isEnabled="true"
            background="transparent" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400" layoutMode="left-to-right"
            lineHeight="1.2" textShadow="" borderColor="#6C757D" borderWidth="0px" iconFontSize="30px"
            ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
            iconFontFamily="font-awesome"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
            ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
            horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
            ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
            horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
            ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
            id="e3fea19e-df8a-425f-9aec-f615f75759da"
            v-bind:style="{'width':'27.549999999999997px','height':'39.9px','zIndex':27,'maxWidth':'','minWidth':'1.9px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'solid','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'2.84886px','borderTopRightRadius':'2.84886px','borderBottomLeftRadius':'2.84886px','borderBottomRightRadius':'2.84886px'}"/>
        </NucGroupElement>
        <TwDescriptionCheckbox v-bind:value="false" headerText="Comments" visibility="visible"
          headerColor="tw-text-gray-700" checkboxAlign="tw-items-start" ncTooltipText="Tooltip text"
          paragraphText="Get notified when someones posts a comment on a posting." headerFontSize="tw-text-sm"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'boolean','propName':'value','displayName':'Value'}]}"
          paragraphColor="tw-text-gray-500" headerFontWeight="tw-font-bold" paragraphFontSize="tw-text-sm"
          paragraphFontWeight="tw-font-light"
          secondParagraphText="Get notified when someones posts a comment on a posting." widthHeightCheckbox="4"
          secondParagraphColor="tw-text-gray-500" secondParagraphFontSize="tw-text-sm"
          secondParagraphFontWeight="tw-font-light" position="absolute" top="55.331215572446276%"
          left="47.40827067669173%" id="35748fe1-da65-4459-abca-6634a4c631dc"
          v-bind:style="{'width':'374.325','height':'67.02199999999999','maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'10.695px','visibility':'visible','marginRight':'0px','paddingLeft':'10.695px','marginBottom':'0px','paddingRight':'10.695px','paddingBottom':'10.695px','zIndex':6}"/>
        <NucCheckbox label="Checkbox" theme="theme--light01" v-bind:value="true" fontSize="14px" v-bind:isEnabled="true"
          textAlign="left" fontFamily="Roboto-Regular,Roboto" fontWeight="normal" ncTypography="custom"
          labelPosition="right" ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'boolean','propName':'value','displayName':'Value'},{'type':'string','propName':'label','displayName':'Display'}]}"
          ncFocusFontColor="black" ncHoverFontColor="black" ncDisableFontColor="black" ncFocusBorderColor="black"
          ncHoverBorderColor="black" ncDisableBorderColor="black" ncFocusBackgroundColor="transparent"
          ncHoverBackgroundColor="transparent" ncDisableBackgroundColor="transparent" position="absolute"
          top="33.14124360109779%" left="31.236842105263158%" id="05829dcf-ead5-46d0-a9c0-630d278d060a"
          v-bind:style="{'color':'','width':'71.3','height':'','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'none','marginTop':'0px','maxHeight':'','minHeight':'','lineHeight':'0.713','marginLeft':'0px','paddingTop':'1.426px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'1.426px','marginBottom':'0px','paddingRight':'1.426px','paddingBottom':'1.426px','textDecoration':'none','zIndex':7}"/>
        <TwDescriptionCheckbox v-bind:value="false" headerText="Comments" visibility="visible"
          headerColor="tw-text-gray-700" checkboxAlign="tw-items-start" ncTooltipText="Tooltip text"
          paragraphText="Get notified when someones posts a comment on a posting." headerFontSize="tw-text-sm"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'boolean','propName':'value','displayName':'Value'}]}"
          paragraphColor="tw-text-gray-500" headerFontWeight="tw-font-bold" paragraphFontSize="tw-text-sm"
          paragraphFontWeight="tw-font-light"
          secondParagraphText="Get notified when someones posts a comment on a posting." widthHeightCheckbox="4"
          secondParagraphColor="tw-text-gray-500" secondParagraphFontSize="tw-text-sm"
          secondParagraphFontWeight="tw-font-light" position="absolute" top="27.039717596737777%"
          left="48.98796992481203%" id="9d3a9499-ca10-4eef-96bf-1b1c2c3fc09c"
          v-bind:style="{'width':'374.325','height':'67.02199999999999','maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'10.695px','visibility':'visible','marginRight':'0px','paddingLeft':'10.695px','marginBottom':'0px','paddingRight':'10.695px','paddingBottom':'10.695px','zIndex':8}"/>
      </NucGroupElement>
    </NucGridCell>
  </NucGridPage>
</template>
<script>
export default {
  name: 'Screen1',
  data() {
    return {};
  },
  props: {},
  created() {},
  mounted() {},
  computed: {},
  methods: {},
  watch: {},
};
</script>

<style scoped></style>